name: Self-Hosted CI

on:
  workflow_dispatch:

env: 
  # DOTNET_VERSION: '3.1.426'
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  Dotnet_Build:
    runs-on: self-hosted  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
  
    - name: Checking Dotnet version
      run: dotnet --version
    - name: Install Dependency
      run: dotnet restore
    - name: Dotnet build
      run: dotnet build -c release
    - name: Dotnet publish
      run: dotnet publish -c release
    - name: UploadArtifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: dotnet_artifacts
        path: bin/release/netcoreapp3.1/publish/aks-ga-demo.dll
      
  # Dotnet_Restore:
  #     runs-on: self-hosted
  #     needs: Dotnet_Install
  #     steps:
  #       - name: Checkout code
  #         uses: actions/checkout@v4
  #       - name: Checking Dotnet version
  #         run: dotnet --version
  #       - name: Install Dependency
  #         run: dotnet restore
  # Dotnet_Build:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Dotnet build
  #       run: dotnet build -c release
  # Dotnet_Publish:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Dotnet build
  #       run: dotnet publish -c release -o /app/publish
  # Listing_Publish_Location:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Listing files
  #       run: |
  #         cd /app/publish
  #         ls -a
          
          
