name: Sonarqube

on:
  workflow_dispatch

jobs:
  Sonarqube:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4.1.2
       - name: Setup Java JDK
         uses: actions/setup-java@v4.2.1
         with:
          java-version: '17'
          distribution: 'adopt'
       - name: Install PostgreSQL
         run: |
            apt update        
            sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'            
            wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
            apt update
            apt-get -y install postgresql postgresql-contrib
            systemctl enable postgresql
            passwd postgres
            su - postgres
            createuser sonar
            psql 
            ALTER USER sonar WITH ENCRYPTED password 'sonar';
            CREATE DATABASE sonarqube OWNER sonar;
            grant all privileges on DATABASE sonarqube to sonar;
            \q  
            exit
       - name: Increase system Limits
         run: |
            sh -c "echo 'sonarqube   -   nofile   65536' >> /etc/security/limits.conf"
            sh -c "echo 'sonarqube   -   nproc    4096' >> /etc/security/limits.conf"
       - name: max map count
         run: sh -c "echo 'vm.max_map_count = 262144' >> /etc/sysctl.conf
       - name: Install Sonarqube
         run: |
            wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.0.65466.zip
            apt install unzip
            unzip sonarqube-9.9.0.65466.zip -d /opt
            mv /opt/sonarqube-9.9.0.65466 /opt/sonarqube
            groupadd sonar
            useradd -c "user to run SonarQube" -d /opt/sonarqube -g sonar sonar
            chown sonar:sonar /opt/sonarqube -R
       - name: Sonar properties
         run: |
           sh -c "echo 'sonar.jdbc.username=sonar' >> /opt/sonarqube/conf/sonar.properties
           sh -c "echo 'sonar.jdbc.password=sonar' >> /opt/sonarqube/conf/sonar.properties
           sh -c "echo 'sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube' >> /opt/sonarqube/conf/sonar.properties
       - name: Start sonar
         run: | 
            systemctl start sonar
            systemctl enable sonar
            systemctl status sonar
            
          
         
 
